# Generated by Django 2.1.7 on 2019-04-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_botuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='group',
        ),
        migrations.DeleteModel(
            name='BotUser',
        ),
    ]
