# Generated by Django 2.1.7 on 2019-09-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_time_table_korpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='added_to_bot',
            field=models.BooleanField(default=False),
        ),
    ]
