# Generated by Django 2.1.7 on 2020-02-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_group_added_to_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCathedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathedra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Cathedra')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Teacher')),
            ],
        ),
    ]
